[project]
name = "factuality"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "asyncio>=4.0.0",
    "black>=26.3.1",
    "bokeh>=3.9.0",
    "datasets>=4.8.4",
    "litellm>=1.83.4",
    "matplotlib>=3.10.9",
    "numpy>=2.2.6",
    "pandas>=2.3.3",
    "pypdf>=6.11.0",
    "requests>=2.33.1",
    "scikit-learn>=1.7.2",
    "scipy>=1.15.3",
    "sentence-transformers>=5.4.1",
    "statsmodels>=0.14.6",
    "tqdm>=4.67.3",
]
